version: '3'

services:
  db:
    image: mysql:5.7
    hostname: mutillidae-db.local
    environment:
      MYSQL_ROOT_PASSWORD: mutillidae
      MYSQL_DATABASE: mutillidae
      MYSQL_PASSWORD: mutillidae

  web:
    build: .
    image: mutillidae
    hostname: mutillidae.local
    depends_on:
      - db
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
